networks:
  app_network:
    driver: bridge
services:
  only-office-app:
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
    extends:
      file: ./services/only-office-app.yaml
      service: app
  ecos-registry-app:
    extends:
      file: ./services/ecos-registry-app.yaml
      service: app
  ecos-proxy-app:
    extends:
      file: ./services/ecos-proxy-app.yaml
      service: app
    depends_on:
      ecos-gateway-app:
        condition: service_healthy
  zookeeper-app:
    extends:
      file: ./services/zookeeper-app.yaml
      service: app
  mailhog-app:
    extends:
      file: ./services/mailhog-app.yaml
      service: app
  rabbitmq-app:
    extends:
      file: ./services/rabbitmq-app.yaml
      service: app
  ecos-identity-app:
    extends:
      file: ./services/ecos-identity-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
  ecos-process-app:
    extends:
      file: ./services/ecos-process-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      mongodb-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  mongodb-app:
    extends:
      file: ./services/mongodb-app.yaml
      service: app
  ecos-model-app:
    extends:
      file: ./services/ecos-model-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-order-pass-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-order-pass-ecos-apps
  ecos-meetings-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-meetings-ecos-apps
  ecos-common-data-list-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-common-data-list-ecos-apps
  ecos-assignments-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-assignments-ecos-apps
  ecos-crm-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-crm-ecos-apps
  ecos-offers-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-offers-ecos-apps
  ecos-time-tracking-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-time-tracking-ecos-apps
  ecos-aro-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-aro-ecos-apps
  ecos-correspondence-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-correspondence-ecos-apps
  ecos-contracts-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-contracts-ecos-apps
  corporate-portal-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: corporate-portal-ecos-apps
  ecos-vacations-ecos-apps:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: ecos-vacations-ecos-apps
  ecos-apps-app:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-gateway-app:
    extends:
      file: ./services/ecos-gateway-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-uiserv-app:
    extends:
      file: ./services/ecos-uiserv-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-history-app:
    extends:
      file: ./services/ecos-history-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-microservices-postgresql-app:
    extends:
      file: ./services/ecos-microservices-postgresql-app.yaml
      service: app
  ecos-notifications-app:
    extends:
      file: ./services/ecos-notifications-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-ecom-app:
    extends:
      file: ./services/ecos-ecom-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-service-desk-app:
    extends:
      file: ./services/ecos-service-desk.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-transformations-app:
    extends:
      file: ./services/ecos-transfomrations-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
