version: '2.4'
networks:
  app_network:
    driver: bridge
services:
  ecos-app:
    extends:
      file: ./services/ecos-app.yaml
      service: app
    depends_on:
      ecos-postgresql-app:
        condition: service_healthy
      ecos-model-app:
        condition: service_healthy
      ecos-search-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-postgresql-app:
    extends:
      file: ./services/ecos-app.yaml
      service: app-db
  ecos-registry-app:
    extends:
      file: ./services/ecos-registry-app.yaml
      service: app
  ecos-search-app:
    extends:
      file: ./services/ecos-search-app.yaml
      service: app
  ecos-proxy-app:
    extends:
      file: ./services/ecos-proxy-app.yaml
      service: app
    depends_on:
      ecos-app:
        condition: service_healthy
  mailhog-app:
    extends:
      file: ./services/mailhog-app.yaml
      service: app
  rabbitmq-app:
    extends:
      file: ./services/rabbitmq-app.yaml
      service: app
  ecos-identity-app:
    extends:
      file: ./services/ecos-identity-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
  ecos-process-app:
    extends:
      file: ./services/ecos-process-app.yaml
      service: app
    depends_on:
      mongodb-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  mongodb-app:
    extends:
      file: ./services/mongodb-app.yaml
      service: app
  ecos-model-app:
    extends:
      file: ./services/ecos-model-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-apps-app:
    extends:
      file: ./services/ecos-apps-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-gateway-app:
    extends:
      file: ./services/ecos-gateway-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-uiserv-app:
    extends:
      file: ./services/ecos-uiserv-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-history-app:
    extends:
      file: ./services/ecos-history-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
  ecos-microservices-postgresql-app:
    extends:
      file: ./services/ecos-microservices-postgresql-app.yaml
      service: app
  ecos-notifications-app:
    extends:
      file: ./services/ecos-notifications-app.yaml
      service: app
    depends_on:
      ecos-microservices-postgresql-app:
        condition: service_healthy
      ecos-registry-app:
        condition: service_healthy
      rabbitmq-app:
        condition: service_healthy
