services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-registry-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/jhipster-registry:v4.1.1
    ports:
      - 8761:8761/tcp
    env_file:
      - ./environments/ecos-registry-app.env
    volumes:
      - ./configs/ecos-registry-app:/central-config
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/management/health"]
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
