version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-microservices-postgresql-app
    restart: always
    stop_grace_period: 1m
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/conf/postgresql.conf"]
    image: nexus.citeck.ru/postgresql:12.7-1
    expose:
      - 5432/tcp
    env_file:
      - ./environments/ecos-microservices-postgresql-app.env
    volumes:
      - ./ecos-community-demo-data/ecos-microservices-postgresql-app:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
