version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-apps-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-apps:2.11.0
    volumes:
      - ./ecos-community-demo-data/ecos-apps:/run/ecos-artifacts/app/ecosapp
    expose:
      - 8089/tcp
    env_file:
      - ./environments/ecos-apps-app.env
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8089/management/health"]
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
  ecos-order-pass-ecos-apps:
    image: nexus.citeck.ru/ecos-order-pass:1.0.0
    environment:
      - ECOS_APPS_TARGET_DIR=/run/ecos-apps-target
    volumes:
      - ./ecos-community-demo-data/ecos-apps:/run/ecos-apps-target
  ecos-meetings-ecos-apps:
    image: nexus.citeck.ru/ecos-meetings:1.2.0
    environment:
      - ECOS_APPS_TARGET_DIR=/run/ecos-apps-target
    volumes:
      - ./ecos-community-demo-data/ecos-apps:/run/ecos-apps-target
  ecos-common-data-list-ecos-apps:
    image: nexus.citeck.ru/ecos-common-data-list:1.0.0
    environment:
      - ECOS_APPS_TARGET_DIR=/run/ecos-apps-target
    volumes:
      - ./ecos-community-demo-data/ecos-apps:/run/ecos-apps-target
  ecos-assignments-ecos-apps:
    image: nexus.citeck.ru/ecos-assignments:1.0.0
    environment:
      - ECOS_APPS_TARGET_DIR=/run/ecos-apps-target
    volumes:
      - ./ecos-community-demo-data/ecos-apps:/run/ecos-apps-target
