version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-notifications-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-notifications:2.13.0
    expose:
      - 8013/tcp
    env_file:
      - ./environments/ecos-notifications-app.env
    volumes:
      - ./configs/ecos-notifications-app:/credentials
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8013/management/health"]
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
