version: '2.4'
services:
  app:
    expose:
      - 8097/tcp
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-ecom-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-ecom:1.2.0
    env_file:
      - ./environments/ecos-ecom-app.env
    networks:
      - app_network
