version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-history-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-history:2.0.0
    expose:
      - 8086/tcp
    env_file:
      - ./environments/ecos-history-app.env
    volumes:
      - /opt/ecos-community-demo-data/ecos-history-app/source:/source
      - /opt/ecos-community-demo-data/ecos-history-app/errors:/errors
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8086/management/health"]
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
