services:
  app:
    expose:
      - 8686/tcp
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-ecom-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-ecom:1.10.0
    env_file:
      - ./environments/ecos-ecom-app.env
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8686/management/health" ]
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
