services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: ecos-transformations-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/ecos-transformations:1.20.0
    ports:
      - 18029:18029/tcp
    environment:
      - SERVER_PORT=18029
    env_file:
      - ./environments/ecos-transformations-app.env
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - 'exec 3<>/dev/tcp/localhost/18029; printf "GET /management/health HTTP/1.0\r\nHost: x\r\n\r\n" >&3; grep -q ''"status":"UP"'' <&3'
      interval: 20s
      timeout: 20s
      retries: 36
    networks:
      - app_network
