services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: mailhog-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025/tcp
    networks:
      - app_network
