version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: mongodb-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/mongo:4.0
    expose:
      - 27017/tcp
    env_file:
      - ./environments/mongodb-app.env
      - ./environments/demo_data.env
    volumes:
      - ./ecos-community-demo-data/mongodb-app:/data/db/
      - ./backups/mongodb-app/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./backups/mongodb-app/mongo:/tmp/mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.getMongo().getDBNames().indexOf('ecos-process') > -1"]
      interval: 10s
      timeout: 20s
      retries: 6
    networks:
      - app_network