version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: mongodb-app
    restart: always
    stop_grace_period: 1m
    image: nexus.citeck.ru/mongo:4.0
    expose:
      - 27017/tcp
    env_file:
      - ./environments/mongodb-app.env
    volumes:
      - /ecos-community-demo-data/mongodb-app:/data/db/
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 20s
      retries: 6
    networks:
      - app_network
