version: '2.4'
services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: rabbitmq-app
    restart: always
    stop_grace_period: 1m
    command: ["/init.sh"]
    image: nexus.citeck.ru/rabbitmq:3.7.18-management-alpine
    expose:
      - 15672/tcp
      - 15692/tcp
    env_file:
      - ./environments/rabbitmq-app.env
    volumes:
      - ./ecos-community-demo-data/rabbitmq-app:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 6
    networks:
      - app_network
