spring:
  datasource:
    url: jdbc:postgresql://ecos-microservices-postgresql-app:5432/ecos_uiserv
    username: uiserv
    password: uiservpassword
config:
  language-switcher-enabled:
    value: true